class Constants:
    ECONOMY = 'Economy'
    CORONA_VIRUS = 'Corona Virus'
    HEALTH_CARE = 'Health Care'
    NATIONAL_SECURITY = 'National Security'
    CLIMATE_CHANGE = 'Climate Change'
    IMMIGRATION = 'Immigration'


    Arizona = 'Arizona'
    Georgia = 'Georgia'
    Florida = 'Florida'
    Nevada = 'Nevada'
    Wisconsin = 'Wisconsin'
    North_Carolina = 'North Carolina'
    Pennsylvania = 'Pennsylvania'
    Ohio = 'Ohio'
    Democrat = 'Democrat'
    Republican = 'Republican'
    Economy = 'Economy'
    Coronavirus = 'Coronavirus'
    Healthcare = 'Healthcare'
    National_Security = 'National Security'
    Climate_Change = 'Climate Change'